server:
  port: 8081

spring:
#  datasource:
#    url: jdbc:dm://localhost:5236?schema=dmdb&useUnicode=true&characterEncoding=utf-8
#    username: SYSDBA
#    password: 12345678aA.
#    driver-class-name: dm.jdbc.driver.DmDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  pagehelper:
    helperDialect: oracle  # 强制使用 Oracle (ROWNUM) 语法，不要自动检测
    reasonable: true
    supportMethodsArguments: true